name: CI/CD Pipeline

on:
 push:
   branches:
     - main
jobs:
  build:
    runs-on: ubuntu-latest
 
     steps:
     - name: Checkout repository
       uses: actions/checkout@v2
                                   
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1

     - name: Log in to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v1

     - name: Build, tag, and push Docker image
       run: |
            REPOSITORY_URI=123683071386.dkr.ecr.us-east-1.amazonaws.com/hello-world-nodejs
            docker build -t $REPOSITORY_URI:latest .
            docker push $REPOSITORY_URI:latest

   deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init                                                                                                                                   
      working-directory: terraform                                                                                                                                          
                                                                                                                                                                            
    - name: Terraform Apply                                                                                                                                                            
      run: terraform apply -auto-approve                                                                                                                                                                 
      working-directory: terraform                                                                                                                                         
                                                                                                                                                                                         
env:
AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}                                                                   
AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

